2023-03-21 17:19:24 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.jincailuo.com/qianming/> (referer: http://www.jincailuo.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\jincailuo.py", line 39, in lists
    num = is_exists({'name':self.name,'url':detail_url})
  File "D:\code\zimeiti\zimeiti\public.py", line 194, in is_exists
    cur.execute(sql)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'cc_11.cc_jincailuo' doesn't exist")
2023-03-21 17:19:24 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.jincailuo.com/xinyu/> (referer: http://www.jincailuo.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\jincailuo.py", line 39, in lists
    num = is_exists({'name':self.name,'url':detail_url})
  File "D:\code\zimeiti\zimeiti\public.py", line 194, in is_exists
    cur.execute(sql)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'cc_11.cc_jincailuo' doesn't exist")
2023-03-21 17:19:24 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.jincailuo.com/mingyan/> (referer: http://www.jincailuo.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\jincailuo.py", line 39, in lists
    num = is_exists({'name':self.name,'url':detail_url})
  File "D:\code\zimeiti\zimeiti\public.py", line 194, in is_exists
    cur.execute(sql)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'cc_11.cc_jincailuo' doesn't exist")
2023-03-21 17:19:24 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.jincailuo.com/jingdianyulu/> (referer: http://www.jincailuo.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\jincailuo.py", line 39, in lists
    num = is_exists({'name':self.name,'url':detail_url})
  File "D:\code\zimeiti\zimeiti\public.py", line 194, in is_exists
    cur.execute(sql)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'cc_11.cc_jincailuo' doesn't exist")
2023-03-21 17:19:24 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.jincailuo.com/kouhao/> (referer: http://www.jincailuo.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\jincailuo.py", line 39, in lists
    num = is_exists({'name':self.name,'url':detail_url})
  File "D:\code\zimeiti\zimeiti\public.py", line 194, in is_exists
    cur.execute(sql)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'cc_11.cc_jincailuo' doesn't exist")
2023-03-21 17:19:24 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.jincailuo.com/zhufuyu/> (referer: http://www.jincailuo.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\jincailuo.py", line 39, in lists
    num = is_exists({'name':self.name,'url':detail_url})
  File "D:\code\zimeiti\zimeiti\public.py", line 194, in is_exists
    cur.execute(sql)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'cc_11.cc_jincailuo' doesn't exist")
2023-03-21 17:19:24 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.jincailuo.com/xiaohua/> (referer: http://www.jincailuo.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\jincailuo.py", line 39, in lists
    num = is_exists({'name':self.name,'url':detail_url})
  File "D:\code\zimeiti\zimeiti\public.py", line 194, in is_exists
    cur.execute(sql)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'cc_11.cc_jincailuo' doesn't exist")
2023-03-21 17:19:24 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.jincailuo.com/shuoshuodaquan/> (referer: http://www.jincailuo.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\jincailuo.py", line 39, in lists
    num = is_exists({'name':self.name,'url':detail_url})
  File "D:\code\zimeiti\zimeiti\public.py", line 194, in is_exists
    cur.execute(sql)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'cc_11.cc_jincailuo' doesn't exist")
2023-03-21 17:19:24 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.jincailuo.com/biaoyu/> (referer: http://www.jincailuo.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\jincailuo.py", line 39, in lists
    num = is_exists({'name':self.name,'url':detail_url})
  File "D:\code\zimeiti\zimeiti\public.py", line 194, in is_exists
    cur.execute(sql)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'cc_11.cc_jincailuo' doesn't exist")
2023-03-21 17:19:24 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.jincailuo.com/juzidaquan/> (referer: http://www.jincailuo.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\jincailuo.py", line 39, in lists
    num = is_exists({'name':self.name,'url':detail_url})
  File "D:\code\zimeiti\zimeiti\public.py", line 194, in is_exists
    cur.execute(sql)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'cc_11.cc_jincailuo' doesn't exist")
2023-03-21 17:20:25 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.jincailuo.com/qianming/> (referer: http://www.jincailuo.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\jincailuo.py", line 39, in lists
    num = is_exists({'name':self.name,'url':detail_url})
  File "D:\code\zimeiti\zimeiti\public.py", line 194, in is_exists
    cur.execute(sql)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'cc_11.cc_jincailuo' doesn't exist")
2023-03-21 17:20:25 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.jincailuo.com/xinyu/> (referer: http://www.jincailuo.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\jincailuo.py", line 39, in lists
    num = is_exists({'name':self.name,'url':detail_url})
  File "D:\code\zimeiti\zimeiti\public.py", line 194, in is_exists
    cur.execute(sql)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'cc_11.cc_jincailuo' doesn't exist")
2023-03-21 17:20:25 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.jincailuo.com/kouhao/> (referer: http://www.jincailuo.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\jincailuo.py", line 39, in lists
    num = is_exists({'name':self.name,'url':detail_url})
  File "D:\code\zimeiti\zimeiti\public.py", line 194, in is_exists
    cur.execute(sql)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'cc_11.cc_jincailuo' doesn't exist")
2023-03-21 17:20:26 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.jincailuo.com/jingdianyulu/> (referer: http://www.jincailuo.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\jincailuo.py", line 39, in lists
    num = is_exists({'name':self.name,'url':detail_url})
  File "D:\code\zimeiti\zimeiti\public.py", line 194, in is_exists
    cur.execute(sql)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'cc_11.cc_jincailuo' doesn't exist")
2023-03-21 17:20:26 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.jincailuo.com/zhufuyu/> (referer: http://www.jincailuo.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\jincailuo.py", line 39, in lists
    num = is_exists({'name':self.name,'url':detail_url})
  File "D:\code\zimeiti\zimeiti\public.py", line 194, in is_exists
    cur.execute(sql)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'cc_11.cc_jincailuo' doesn't exist")
2023-03-21 17:20:26 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.jincailuo.com/xiaohua/> (referer: http://www.jincailuo.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\jincailuo.py", line 39, in lists
    num = is_exists({'name':self.name,'url':detail_url})
  File "D:\code\zimeiti\zimeiti\public.py", line 194, in is_exists
    cur.execute(sql)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'cc_11.cc_jincailuo' doesn't exist")
2023-03-21 17:20:26 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.jincailuo.com/biaoyu/> (referer: http://www.jincailuo.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\jincailuo.py", line 39, in lists
    num = is_exists({'name':self.name,'url':detail_url})
  File "D:\code\zimeiti\zimeiti\public.py", line 194, in is_exists
    cur.execute(sql)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'cc_11.cc_jincailuo' doesn't exist")
2023-03-21 17:20:26 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.jincailuo.com/mingyan/> (referer: http://www.jincailuo.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\jincailuo.py", line 39, in lists
    num = is_exists({'name':self.name,'url':detail_url})
  File "D:\code\zimeiti\zimeiti\public.py", line 194, in is_exists
    cur.execute(sql)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'cc_11.cc_jincailuo' doesn't exist")
2023-03-21 17:20:26 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.jincailuo.com/shuoshuodaquan/> (referer: http://www.jincailuo.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\jincailuo.py", line 39, in lists
    num = is_exists({'name':self.name,'url':detail_url})
  File "D:\code\zimeiti\zimeiti\public.py", line 194, in is_exists
    cur.execute(sql)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'cc_11.cc_jincailuo' doesn't exist")
2023-03-21 17:20:26 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.jincailuo.com/juzidaquan/> (referer: http://www.jincailuo.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\jincailuo.py", line 39, in lists
    num = is_exists({'name':self.name,'url':detail_url})
  File "D:\code\zimeiti\zimeiti\public.py", line 194, in is_exists
    cur.execute(sql)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'cc_11.cc_jincailuo' doesn't exist")
2023-03-22 14:48:25 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.etgushi.com/jdth/> (referer: https://www.etgushi.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\etgushi.py", line 47, in lists
    detail_url = urljoin(repsonse.url,li)
  File "D:\Anaconda3\envs\scrapy\lib\urllib\parse.py", line 487, in urljoin
    base, url, _coerce_result = _coerce_args(base, url)
  File "D:\Anaconda3\envs\scrapy\lib\urllib\parse.py", line 120, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments
2023-03-22 14:48:51 [scrapy.utils.log] INFO: Scrapy 2.8.0 started (bot: zimeiti)
2023-03-22 14:48:51 [scrapy.utils.log] INFO: Versions: lxml 4.9.2.0, libxml2 2.9.12, cssselect 1.2.0, parsel 1.7.0, w3lib 2.1.1, Twisted 22.4.0, Python 3.7.0 | packaged by conda-forge | (default, Nov 12 2018, 20:47:31) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 23.0.0 (OpenSSL 3.0.8 7 Feb 2023), cryptography 39.0.2, Platform Windows-10-10.0.19041-SP0
2023-03-22 14:48:51 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'zimeiti',
 'FEED_EXPORT_ENCODING': 'utf-8',
 'LOG_FILE': 'log.txt',
 'NEWSPIDER_MODULE': 'zimeiti.spiders',
 'REQUEST_FINGERPRINTER_IMPLEMENTATION': '2.7',
 'SPIDER_MODULES': ['zimeiti.spiders'],
 'TWISTED_REACTOR': 'twisted.internet.asyncioreactor.AsyncioSelectorReactor'}
2023-03-22 14:48:51 [asyncio] DEBUG: Using selector: SelectSelector
2023-03-22 14:48:51 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.asyncioreactor.AsyncioSelectorReactor
2023-03-22 14:48:51 [scrapy.utils.log] DEBUG: Using asyncio event loop: asyncio.windows_events._WindowsSelectorEventLoop
2023-03-22 14:48:51 [scrapy.extensions.telnet] INFO: Telnet Password: 8bbe51f1b94f2e25
2023-03-22 14:48:51 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2023-03-22 14:48:51 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2023-03-22 14:48:51 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2023-03-22 14:48:51 [scrapy.middleware] INFO: Enabled item pipelines:
['zimeiti.pipelines.ZimeitiPipeline']
2023-03-22 14:48:51 [scrapy.core.engine] INFO: Spider opened
2023-03-22 14:48:51 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2023-03-22 14:48:51 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6026
2023-03-22 14:48:51 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.etgushi.com/> (referer: None)
2023-03-22 14:48:51 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.etgushi.com/jdth/> (referer: https://www.etgushi.com/)
2023-03-22 14:48:51 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.etgushi.com/jdth/> (referer: https://www.etgushi.com/)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\Anaconda3\envs\scrapy\lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "D:\code\zimeiti\zimeiti\spiders\etgushi.py", line 47, in lists
    detail_url = urljoin(repsonse.url,li)
  File "D:\Anaconda3\envs\scrapy\lib\urllib\parse.py", line 487, in urljoin
    base, url, _coerce_result = _coerce_args(base, url)
  File "D:\Anaconda3\envs\scrapy\lib\urllib\parse.py", line 120, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments
2023-03-22 14:48:51 [scrapy.core.engine] INFO: Closing spider (finished)
2023-03-22 14:48:51 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 624,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 14700,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 2,
 'elapsed_time_seconds': 0.411736,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2023, 3, 22, 6, 48, 51, 848610),
 'httpcompression/response_bytes': 45971,
 'httpcompression/response_count': 2,
 'log_count/DEBUG': 5,
 'log_count/ERROR': 1,
 'log_count/INFO': 10,
 'request_depth_max': 1,
 'response_received_count': 2,
 'scheduler/dequeued': 2,
 'scheduler/dequeued/memory': 2,
 'scheduler/enqueued': 2,
 'scheduler/enqueued/memory': 2,
 'spider_exceptions/TypeError': 1,
 'start_time': datetime.datetime(2023, 3, 22, 6, 48, 51, 436874)}
2023-03-22 14:48:51 [scrapy.core.engine] INFO: Spider closed (finished)
